spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pathfinder_db?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
        ddl-auto: update
    application:
      name: pathfinder_db
    mvc:
      hiddenmethod:
        filter:
          enabled: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN